### ISSUE TITLE
Error open

### ISSUE THREAD

**Issue by deletron247** [An0nimia/DeezloaderAn0n_bot#21]
Traceback (most recent call last):
  File "dwsongs-normal.py", line 53, in <module>
    downloa = Login(deezer_token)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/deezloader/__init__.py", line 37, in __init__
    raise exceptions.BadCredentials("Wrong token: %s :(" % token)
deezloader.exceptions.BadCredentials: Wrong token:

**Comment by Mushebeq** [comment]
Go get your arl token from Deezer.com
