### ISSUE TITLE
\info command went wrong

### ISSUE THREAD

**Issue by starfall1991** [An0nimia/DeezloaderAn0n_bot#27]
2020-05-14 10:49:37,824 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/####/.local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 343, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/####/.local/lib/python3.6/site-packages/telegram/ext/handler.py", line 119, in handle_update
    return self.callback(update, context)
  File "dwsongs-normal.py", line 1487, in menu
    statisc(chat_id, "TRACKS")
TypeError: %d format: a number is required, not str

what exactly happened ?

**Comment by Mushebeq** [comment]
Works fine here. Did you modify the script?

**Comment by starfall1991** [comment]
thank you for the reply I will check my modifications

**Comment by destroyer19991** [comment]
works fine here too
