### ISSUE TITLE
Spotify URL Issues, Error I get At The console

### ISSUE THREAD

**Issue by adoboligh1** [An0nimia/DeezloaderAn0n_bot#39]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "dwsongs-normal.py", line 364, in Link
    link = what_kind(link)
  File "/usr/local/lib/python3.6/site-packages/deezloader/utils.py", line 275, in what_kind
    url = request(link).url
  File "/usr/local/lib/python3.6/site-packages/deezloader/utils.py", line 61, in request
    thing = get(url, headers = header)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'Powered By TeleFeed': No schema supplied. Perhaps you meant http://Powered By TeleFeed?

**Comment by adoboligh1** [comment]
I get an invalid link when i send a spotify URL at the Bot
