### ISSUE TITLE
Something went wrong with configuration file

### ISSUE THREAD

**Issue by 9Mad-Max5** [An0nimia/DeezloaderAn0n_bot#7]
Hi,

Im getting this issue.
I don´t get why.

**Comment by 9Mad-Max5** [comment]
For sure can have a look.
But there wasn´t a " in the template.
`[login]
mail = ikariam.Ambrosia@gmx.de
password = NBdhk1mm0RaqRrA3rQ85
token = 674e0592c1d7020ee06d03faeadf75e3601c07464e9ca5adeaa6126eb03c89fa5f9c00c8c3987acb99debe3b41d7a7ff96615d594024f0e027c946e23501669f897a2e70a0fea45bd0dab5e097f788e$

[bot]
token = 939900920:AAHtphnVo9aiswDJ_txdulxEBt42A9FwnHA

[acrcloud]
key = ec64ba806337076d
secret = a4018398cbc0990c5711c79e4aef4b9f
host = https://identify-eu-west-1.acrcloud.com

[yandex]
key = trnsl.1.1.20181114T193428Z.ec0fb3fb93e116c0.24b2ccfe2d150324e23a5571760e9a827d953003

[bot_info]
version = 2.0
creator = An0nimia
donation = https://www.paypal.me/An0nimia
group = https://t.me/DeezloaderRMX_group
`

**Comment by An0nimia** [comment]
the Yandex Key maybe?

**Comment by An0nimia** [comment]
Wait what stupid, say me what is your error first

**Comment by An0nimia** [comment]
Open the script find the first KeyError and replace it with KeyboardInterrupt and say me the traceback

**Comment by 9Mad-Max5** [comment]
Ah sorry,

I made a fast issue.
The Errortext is:
Something went wrong with configuration file

And as i found i just came up once.

`except KeyError:
        print("Something went wrong with configuration file")
        sys.exit(0)
`
I didn´t change the yandex key

**Comment by An0nimia** [comment]
@9Mad-Max5 Replace that KeyError with KeyboardInterrupt, execute the script and say me the output

**Comment by 9Mad-Max5** [comment]
Traceback (most recent call last):
  File "./DeezloaderAn0n_bot/dwsongs-normal.py", line 34, in <module>
    mail = config['login']['mail']
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'login'

**Comment by An0nimia** [comment]
@9Mad-Max5 Delete that ` in the ini file

**Comment by 9Mad-Max5** [comment]
@ uff.
Sorry its not part of the ini file.
``
its the quatition for code in github.

**Comment by An0nimia** [comment]
@9Mad-Max5 This is getting strange

**Comment by 9Mad-Max5** [comment]
Arghhhh.
Ok clicked the wrong button.
could there be an issue with the mail format in the ini file?
i have a mail which is seperated by an .

**Comment by An0nimia** [comment]
@An0nimia Are you sure that is the only setting.ini file?

**Comment by 9Mad-Max5** [comment]
Yep im pretty sure

**Comment by An0nimia** [comment]
@9Mad-Max5 Okay let do this copy your ini content file on a free paste site and give me the link

**Comment by Lokke** [comment]
> Traceback (most recent call last):
> File "./DeezloaderAn0n_bot/dwsongs-normal.py", line 34, in
> mail = config['login']['mail']
> File "/usr/lib/python3.5/configparser.py", line 956, in **getitem**
> raise KeyError(key)
> KeyError: 'login'

same for me 
mail is seperated my dot "." - password starting with bang "!"
since you are using the script right now i assume that you got it running - may you'll tell me your solution?

**Comment by Lokke** [comment]
https://hastebin.com/ikimefufel.makefile

**Comment by Lokke** [comment]
installed python modules: https://hastebin.com/micotuqabu.css
